version: '3.8'

services:

  # 我的SpringBoot项目 配置
  app:
    build: .                          # 【核心】告诉 Docker 在当前docker-compose.yml的目录下寻找 Dockerfile 文件，并构建镜像
    container_name: dining-app
    ports:
      - "8080:8080"
    depends_on:                       # 启动顺序依赖：先启动 redis、rabbitmq 容器，再启动 app 容器
      - redis
      - rabbitmq
    environment:
      TZ: Asia/Shanghai               # 设置系统环境变量。把容器内的时区设为上海，这能防止项目输出到日志文件的时间有时间差问题
    restart: always                   # 重启策略：如果 app 容器(我的SpringBoot项目)意外重启 / Down掉，Docker 会自动把它重新拉起来
    # 挂载外部配置：服务器上config文件夹内的application-pro.yml配置 (这一步是在Linux服务器拉取git代码之前提前写好的，到服务器上手动创建application-pro.yml写连接数据后，就能在启动时使用这个配置)
    volumes:
      - ./config/application-pro.yml:/app/config/application-pro.yml


  # Redis 配置
  redis:                              # 服务名
    image: redis:7-alpine             # 直接拉取现成的官方 Redis 镜像，不用写 Dockerfile 自己构建 (与build作用相反)
    container_name: dining-redis      # 自定义容器名，方便后面 docker ps 时能区分
    command: redis-server --requirepass "123456"    # 容器启动时直接设置密码
    ports:
      - "6379:6379"
    restart: always                   # 重启策略：如果 Redis 意外重启 / 项目崩溃退出了，Docker 会自动把它重新拉起来 (必要前提:我的Docker设置了开机自启)


  # RabbitMQ 配置
  rabbitmq:
    image: rabbitmq:3-management      # 直接拉取现成的官方 RabbitMQ 镜像
    container_name: dining-rabbitmq
    ports:
      - "5672:5672"                   # amqp端口
      - "15672:15672"                 # web管理后台
    environment:
      RABBITMQ_DEFAULT_USER: admin    # 这两行含义：容器启动时创建管理员账号(如果不写这两行，默认只有guest账号，容器之间无法使用guest连接会报错，所以MQ强烈建议手动指定账号)
      RABBITMQ_DEFAULT_PASS: 123456
    restart: always

