<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Maven经典的“三家伙”（GAV坐标），用于在仓库中唯一标识当前项目 -->
    <groupId>com.aqinyo</groupId>   <!-- 当前Maven项目隶属组织名称 -->
    <artifactId>Dining_service_platform</artifactId><!-- 当前 Maven项目名称 -->
    <version>1.0-SNAPSHOT</version>


    <!-- 打包类型为pom: 表示当前工程是一个父子聚合工程，本身不包含业务代码。父工程不会生成jar或war文件，仅生成pom文件。而子工程则根据实际需要设置为jar或war -->
    <packaging>pom</packaging>


    <!--  <modules> 标签负责聚合子工程，声明了当前父工程所包含的子模块 -->
    <modules>
        <module>dining-common</module>
        <module>dining-model</module>
        <module>dining-server</module>
    </modules>


    <!-- SpringBoot项目需要继承 "父工程"  (后面添加进SpringBoot项目所涉及到的依赖，都不需要加version,因为父工程都统一管理) -->
    <parent>
        <artifactId>spring-boot-starter-parent</artifactId>
        <groupId>org.springframework.boot</groupId>
        <version>2.7.3</version>
    </parent>


    <!-- 在<properties>中存放的是【Spring Boot 父工程未统一管理的依赖】并手动指定了版本
         其中既有第三方中间件/服务（如 MyBatis、Druid、阿里云OSS、Knife4j），也有工具类库（如 Lombok、Fastjson、Commons-lang），还有基础组件（如 AspectJ、JAXB）
         如果未来需要升级某个依赖（如 lombok），只需在此处修改一次版本号，所有引用该属性的依赖都会自动生效，避免了多处重复配置和修改带来的维护成本  -->
    <properties>
        <mybatis.spring>2.2.0</mybatis.spring>
        <lombok>1.18.30</lombok>
        <fastjson>1.2.76</fastjson>
        <commons.lang>2.6</commons.lang>
        <druid>1.2.1</druid>
        <pagehelper>1.3.0</pagehelper>
        <aliyun.sdk.oss>3.10.2</aliyun.sdk.oss>
        <knife4j>3.0.2</knife4j>
        <aspectj>1.9.4</aspectj>
        <jjwt>0.9.1</jjwt>
        <jaxb-api>2.3.1</jaxb-api>
    </properties>


    <dependencyManagement>
        <dependencies>
        <!-- 下面各个 <dependency> 的 <version> 是通过 ${属性名} 来引用上面<properties>中统一的值（例如 ${mybatis.spring}） -->
            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis.spring}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson}</version>
            </dependency>

            <dependency>
                <groupId>commons-lang</groupId>
                <artifactId>commons-lang</artifactId>
                <version>${commons.lang}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid}</version>
            </dependency>

            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>${pagehelper}</version>
            </dependency>

            <!-- knife4j 4+  openapi3 启动器: server 子模块使用 -->
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
                <version>4.3.0</version>    <!-- 使用openapi3对应版本 -->
            </dependency>
            <!-- springdoc: common、model 子模块使用（仅注解@Schema）（父工程这虽有引用，但更像声明依赖，在子模块中才是实际引用） -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-common</artifactId>
                <version>2.2.0</version>
            </dependency>

            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjrt</artifactId>
                <version>${aspectj}</version>
            </dependency>

            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjweaver</artifactId>
                <version>${aspectj}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt</artifactId>
                <version>${jjwt}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>${aliyun.sdk.oss}</version>
            </dependency>

            <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>${jaxb-api}</version>
            </dependency>

            <!--微信支付-->
            <dependency>
                <groupId>com.github.wechatpay-apiv3</groupId>
                <artifactId>wechatpay-apache-httpclient</artifactId>
                <version>0.4.8</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
