<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>dining-model</artifactId>


    <!-- <parent> 标签用于声明当前子工程所继承的父工程。里面的三个子标签（父工程的GAV坐标）则用于在Maven中定位唯一父工程 -->
    <parent>
        <!-- 父工程隶属的组织名称 -->
        <groupId>com.aqinyo</groupId>
        <!-- 父工程的项目名称 -->
        <artifactId>Dining_service_platform</artifactId>
        <!-- 父工程的版本号 -->
        <version>1.0-SNAPSHOT</version>
    </parent>


    <dependencies>
        <!-- 下面各个依赖的版本，已经在父工程中被统一管理了 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>

        <!-- model子模块只需要@Schema等注解,不用UI增强,所以单独引入io.swagger.core.v3:swagger-annotations:2.2.10 依赖即可,只提供@Schema纯注解 (父工程虽有引用但更像声明依赖，在子模块中才是实际引用) -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.2.10</version>
        </dependency>

    </dependencies>

</project>
