<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>dining-server</artifactId>


    <!-- <parent> 标签用于声明当前子工程所继承的父工程。里面的三个子标签（父工程的GAV坐标）则用于在Maven中定位唯一父工程 -->
    <parent>
        <!-- 父工程隶属的组织名称 -->
        <groupId>com.aqinyo</groupId>
        <!-- 父工程的项目名称 -->
        <artifactId>Dining_service_platform</artifactId>
        <!-- 父工程的版本号 -->
        <version>1.0-SNAPSHOT</version>
    </parent>


    <dependencies>
        <!-- 下面各个依赖的版本，已经在父工程中被统一管理了 -->

        <!-- 添加server模块,所需要依赖的 dining-common、dining-model 两个子模块 -->
        <dependency>
            <groupId>com.aqinyo</groupId>
            <artifactId>dining-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.aqinyo</groupId>
            <artifactId>dining-model</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- 添加server模块,所依赖的 Spring Boot 框架 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- Spring Test 框架依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- mockito-inline: 支持 Mock 静态方法 (如 HttpClientUtil.doGet) -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Spring MVC 框架 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>compile</scope>
        </dependency>

        <!-- MySQL 连接驱动依赖 -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

        <!-- Spring Boot 整合 MyBatis 框架的起步依赖 -->
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
        </dependency>

        <!-- Lombok 框架 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- 阿里巴巴 -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
        </dependency>

        <!-- PageHelper 分页插件的依赖 -->
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
        </dependency>

        <!-- AOP切面的依赖 -->
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
        </dependency>

        <!-- knife4j 是用于 "自动生成接口文档" 的依赖 (是Swagger的增强UI) -->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
        </dependency>

        <!-- 基于Spring Data Redis 操作 Redis 的起步依赖 (推荐使用,不推荐Jedis) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <!-- 基于Spring Cache 注解式 操作 Redis 的起步依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>

        <!-- jaxb-api 依赖: 用于解决Java11+版本中jaxb被移除后，Knife4j/Swagger等组件因缺少该模块而引发的NoClassDefFoundError异常 -->
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>

        <!-- 引入RabbitMQ所需依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>

        <!-- 引入Spring Boot Actuator 依赖: 用于监控和管理 Spring Boot 应用 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

    </dependencies>


    <!-- 这里主要作用是: 将 Spring Boot 项目打包成可执行的 jar包 -->
    <build>     <!-- <build> 标签：用于配置项目的构建过程 -->
        <plugins>   <!-- <plugins> 标签：用于声明构建时需要使用的 Maven 插件集合 -->
            <plugin>    <!-- <plugin> 标签：声明具体的 Maven 插件 -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>   <!-- spring-boot-maven-plugin：Spring Boot 提供的Maven插件 -->
            </plugin>
        </plugins>
    </build>


</project>
