server:       # 设置 Spring Boot 服务的业务端口
  port: 8080  # dev环境也是8080端口 (因为激活之后会覆盖原本的端口,所以干脆dev和原本的一致) / test环境是8081端口 / pro环境是8082端口


spring:       # Spring Boot 服务的配置 (一定要注意层级关系,不能写错,必须是在Spring下的)

  profiles:       # 利用 profiles功能 进行"动态配置切换"
    active: dev   # 激活 dev开发环境配置  (打包依然正常打包，不改动IDEA内激活配置。虚拟机/线上 部署启动jar时，再切换为 pro 激活即可)

  main:
    allow-circular-references: true   # Spring Boot 2.6+ 默认禁止了Bean的循环依赖，设置为true可以允许循环引用，避免项目启动时因循环依赖报错

  # 在.yml上依旧是用引用符号替代,具体的值我们写在-dev.yml当中   (属于"属性占位符"引用方式,引用其他配置文件的属性,好处:环境隔离、集中管理、避免了硬编码)
  datasource:
      driver-class-name: ${Dining.datasource.driver-class-name}
      url: "jdbc:mysql://${Dining.datasource.host}:${Dining.datasource.port}/${Dining.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true"
      username: ${Dining.datasource.username}
      password: ${Dining.datasource.password}


  redis:
    host: ${Dining.redis.host}
    port: ${Dining.redis.port}
    password: ${Dining.redis.password}
    database: ${Dining.redis.database}


  rabbitmq:
    host: ${Dining.rabbitmq.host}
    port: ${Dining.rabbitmq.port}
    username: ${Dining.rabbitmq.username}
    password: ${Dining.rabbitmq.password}
    virtual-host: ${Dining.rabbitmq.virtual-host}
    # 消息可靠性: 生产者-消息确认机制 (confirm + returns) (Confirm机制对应 ConfirmCallback, Return机制对应 ReturnsCallback)
    publisher-confirm-type: correlated    # 开启生产者 confirm 机制 (异步回调): 确认消息是否成功到达Exchange, 到达后会异步调用 ConfirmCallback 返回 ack/nack 给生产者
    publisher-returns: true               # 开启生产者 returns 机制:         确认消息是否成功路由到Queue, "路由失败"时触发 ReturnsCallback 将消息退回 给生产者
    template:
      mandatory: true                     # 定义(return机制)"消息路由失败"的策略 --> true:则调用 ReturnsCallback / false:则直接丢弃消息
    # 消息可靠性: 消费者-消息确认机制
    listener:
      simple:
        acknowledge-mode: auto            # 自动确认模式
        default-requeue-rejected: false   # 重试耗尽后不重新入队(防止无限循环), 直接reject/nack --> 进入fallback兜底队列
        # 消息可靠性: 消费者 - 消费失败重试机制
        retry:
          enabled: true                   # 开启消费者本地重试: 指在消费者应用内存中拦截异常并重试，而不再重新入RabbitMQ  (常用于应对消费者的网络波动时)
          max-attempts: 3                 # 最多重试3次          (本地重试只是第一道防线，并非保证消息100%能被消费！若重试耗尽仍失败则需要进入死信队列,发挥死信交换机的消息的兜底机制，这是最后的屏障，最后交由人工处理)
          initial-interval: 3000          # 失败重试时间间隔3s


# MyBatis应该也是要配置的,但我使用的Mapper自动代理很规范(目录结构对应上、XML文件全限定类名也对应上),所以这里就不需要配置了,都与默认的MyBatis配置内容一致
mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml  # 指定MyBatis的Mapper XML文件位置
  type-aliases-package: com.aqinyo.entity   # 给指定包下的实体类起别名，配置后，在Mapper XML文件中写resultType等参数时，可以直接写实体类名，不需要写全限定类名，比如原来要写com.aqinyo.entity.User，现在直接写User就行
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true


logging:
  level:
    com:
      aqinyo:
        mapper: debug
        service: info
        controller: info


aqinyo:
  jwt:
    # Admin 商家端
    admin-secret-key: aqinyoAdminSecretJWT  # 设置admin的jwt签名加密时使用的秘钥 (自定义)
    admin-ttl: 7200000          # 这里设置JWT的token令牌有效期为2h
    admin-token-name: token     # 设置前端传递过来的令牌名 (B端和C端的令牌名不要同名)

    # User 用户端
    user-secret-key: aqyinyoUserSecretJWT
    user-ttl: 7200000
    user-token-name: authentication


  alioss:
    endpoint: ${Dining.alioss.endpoint}
    access-key-id: ${Dining.alioss.access-key-id}
    access-key-secret: ${Dining.alioss.access-key-secret}
    bucket-name: ${Dining.alioss.bucket-name}

    # 图片上传安全与大小限制 (需在后端代码中结合 MultipartFile 进行拦截校验)
    allowed-image-types: jpg,jpeg,png,gif,webp    # 允许的图片格式白名单 (严格限制后缀，防止恶意脚本/木马上传)
    max-image-size: 5MB                           # 图片最大限制 (企业主流建议 2MB~5MB，兼顾清晰度与页面加载速度)

    # 文件上传安全与大小限制 (需在后端代码中结合 MultipartFile 进行拦截校验)
    max-file-size: 50MB                           # 普通文件最大限制 (如文档、短视频，超大文件建议前端采用分片上传)
    allowed-file-types: pdf,doc,docx,xls,xlsx,mp4 # 允许的文件格式白名单


  wechat:
    appid: ${Dining.wechat.appid}
    secret: ${Dining.wechat.secret}


# Actuator  (目前可视化是通过网页简单验证,为后续生产环境可视化监控提供支持,提前打好基础: 云监控 / 引入Prometheus + Grafana)
management:
  server:
    port: 8088    # 监控端口和业务端口分离 [应对"端点暴露"问题]

  endpoints:
    web:          # 配置 Web端点
      base-path: /aqinyo_actuator   # 修改默认 /actuator 路径 [应对"端点暴露"问题]
      exposure:                     # 暴露Actuator的监控端点给Web访问
        include: health,info,metrics,beans,conditions,threaddump   # 可以按需选择端点暴露 (高危端点：env、heapdump、threaddump) [应对"端点暴露"问题]

  endpoint:
    health:       # 配置 健康检查端点
      show-details: always          # 显示健康检查的详细信息
      probes:
        enabled: true               # 显示开启 K8s 探针支持
      diskspace:
        enabled: true               # 显示开启 磁盘空间检查
        threshold: 10MB             # 剩余空间小于10MB时标记为不健康
    env:          # 配置 Env(环境变量)端点
      show-values: always           # 显示环境变量的任何具体值 (注意:在生产环境这里必须是never!)[应对"敏感数据暴露"问题]

